# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Valliappan
email: ganeshv757@gmail.com
description: Hi, I am Ganesh Valliappan, an aspiring free-lance programmer in the Silicon Valley!
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://theganv.co" # the base hostname & protocol for your site
twitter_username: GanV757
github_username:  GaneshV757

# Build settings
markdown: kramdown
